In [1]:
import numpy as np 

arr = np.array([1, 2, 3, 4, 5] , dtype = np.float32)

print(repr(arr))

array([1., 2., 3., 4., 5.], dtype=float32)


In [2]:
arr= np.array([1,2,3,4,5,6,7,8,9,10])

odd_arr = arr[list(range(1, len(arr), 2))]
even_arr = arr[list(range(0, len(arr), 2))]
print(odd_arr)
print(even_arr)

[ 2  4  6  8 10]
[1 3 5 7 9]


## Numpy Basics


## A. Ranged data

In [3]:
arr = np.arange(5)
print(repr(arr))

arr = np.arange(5.1)
print(repr(arr))

arr = np.arange(-1, 4)
print(repr(arr))

arr = np.arange(-1.5, 4, 2)
print(repr(arr))

array([0, 1, 2, 3, 4])
array([0., 1., 2., 3., 4., 5.])
array([-1,  0,  1,  2,  3])
array([-1.5,  0.5,  2.5])


In [4]:
arr = np.linspace(5, 11, num=4)
print(repr(arr))

arr = np.linspace(5, 11, num=4, endpoint=False)
print(repr(arr))

arr = np.linspace(5, 11, num=4, endpoint=True)
print(repr(arr))

arr = np.linspace(5, 11, num=4, dtype=np.int32)
print(repr(arr))

array([ 5.,  7.,  9., 11.])
array([5. , 6.5, 8. , 9.5])
array([ 5.,  7.,  9., 11.])
array([ 5,  7,  9, 11], dtype=int32)


## B. Reshaping data

In [5]:
arr = np.arange(8)

reshaped_arr = np.reshape(arr, (2, 4))
print(repr(reshaped_arr))
print('New shape: {}'.format(reshaped_arr.shape))

reshaped_arr = np.reshape(arr, (-1, 2, 2))
print(repr(reshaped_arr))
print('New shape: {}'.format(reshaped_arr.shape))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])
New shape: (2, 4)
array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])
New shape: (2, 2, 2)


In [6]:
arr = np.arange(10)
arr = np.reshape(arr, (2, 5))
flattened = arr.flatten()
print(repr(arr))
print('arr shape: {}'.format(arr.shape))
print(repr(flattened))
print('flattened shape: {}'.format(flattened.shape))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])
arr shape: (2, 5)
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
flattened shape: (10,)


## C. Transposing

In [7]:
arr = np.arange(10)
arr= np.reshape(arr, (2, 5))
transp = np.transpose(arr)

print(repr(arr))
print('arr shape: {}'.format(arr.shape))
print(repr(transp))
print('transp shape: {}'.format(transp.shape))


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])
arr shape: (2, 5)
array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])
transp shape: (5, 2)


In [8]:
arr2 = np.arange(10).reshape(2, 5)
print(repr(arr2))
arr3 = np.arange(24)
arr3 = np.reshape(arr3, (3, 2, 4))
print(repr(arr3))
print('arr3 shape: {}'.format(arr3.shape))
transposed = np.transpose(arr3, axes = (1,2,0))
print(repr(transposed))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])
arr3 shape: (3, 2, 4)
array([[[ 0,  8, 16],
        [ 1,  9, 17],
        [ 2, 10, 18],
        [ 3, 11, 19]],

       [[ 4, 12, 20],
        [ 5, 13, 21],
        [ 6, 14, 22],
        [ 7, 15, 23]]])


`axes parameter: Specifies the new order of axes for the transposed array. In this case, (1, 2, 0) means:
The first axis (0) of arr becomes the third axis in the transposed array.
The second axis (1) of arr becomes the first axis in the transposed array.
The third axis (2) of arr becomes the second axis in the transposed array.`

## D. Zeros and ones

In [9]:
arr = np.zeros(4)
print(repr(arr))

arr = np.ones((2, 3))
print(repr(arr))

arr = np.ones((2, 3), dtype=np.int32)
print(repr(arr))

array([0., 0., 0., 0.])
array([[1., 1., 1.],
       [1., 1., 1.]])
array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)


In [10]:
arr = np.array([[1, 2], [3, 4]])
print(repr(np.zeros_like(arr)))

arr = np.array([[0., 1.], [1.2, 4.]])
print(repr(np.ones_like(arr)))
print(repr(np.ones_like(arr, dtype=np.int32)))

array([[0, 0],
       [0, 0]])
array([[1., 1.],
       [1., 1.]])
array([[1, 1],
       [1, 1]], dtype=int32)


## A. Arithmetic

In [11]:
arr = np.array([[1, 2], [3, 4]])
# Add 1 to element values
print(repr(arr + 1))
# Subtract element values by 1.2
print(repr(arr - 1.2))
# Double element values
print(repr(arr * 2))
# Halve element values
print(repr(arr / 2))
# Integer division (half)
print(repr(arr // 2))
# Square element values
print(repr(arr**2))
# Square root element values
print(repr(arr**0.5))

array([[2, 3],
       [4, 5]])
array([[-0.2,  0.8],
       [ 1.8,  2.8]])
array([[2, 4],
       [6, 8]])
array([[0.5, 1. ],
       [1.5, 2. ]])
array([[0, 1],
       [1, 2]])
array([[ 1,  4],
       [ 9, 16]])
array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])


In [12]:
def f2c(temps):
  return (5/9)*(temps-32)

fahrenheits = np.array([32, -4, 14, -40])
celsius = f2c(fahrenheits)
print('Celsius: {}'.format(repr(celsius)))

Celsius: array([  0., -20., -10., -40.])


## B. Non-linear functions

In [13]:
arr = np.array([[1, 2], [3, 4]])
# Raised to power of e
print(repr(np.exp(arr)))
# Raised to power of 2
print(repr(np.exp2(arr)))

arr2 = np.array([[1, 10], [np.e, np.pi]])
# Natural logarithm
print(repr(np.log(arr2)))
# Base 10 logarithm
print(repr(np.log10(arr2)))

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])
array([[ 2.,  4.],
       [ 8., 16.]])
array([[0.        , 2.30258509],
       [1.        , 1.14472989]])
array([[0.        , 1.        ],
       [0.43429448, 0.49714987]])


In [14]:
arr = np.array([[1, 2], [3, 4]])
# Raise 3 to power of each number in arr
print(repr(np.power(3, arr)))
arr2 = np.array([[10.2, 4], [3, 5]])
# Raise arr2 to power of each number in arr
print(repr(np.power(arr2, arr)))

array([[ 3,  9],
       [27, 81]])
array([[ 10.2,  16. ],
       [ 27. , 625. ]])


## C. Matrix multiplication

In [15]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([-3, 0, 10])
print(np.matmul(arr1, arr2))

arr3 = np.array([[1, 2], [3, 4], [5, 6]])
arr4 = np.array([[-1, 0, 1], [3, 2, -4]])
print(repr(np.matmul(arr3, arr4)))
print(repr(np.matmul(arr4, arr3)))
# This will result in a ValueError: If we uncomment line 10 and run again.
#print(repr(np.matmul(arr3, arr3)))

arr5 = arr3@arr4
print((arr5))

27
array([[  5,   4,  -7],
       [  9,   8, -13],
       [ 13,  12, -19]])
array([[  4,   4],
       [-11, -10]])
[[  5   4  -7]
 [  9   8 -13]
 [ 13  12 -19]]


## Random

In [16]:
print(np.random.randint(5))
print(np.random.randint(5))
print(np.random.randint(5, high=6))

random_arr = np.random.randint(-3, high=14,
                               size=(2, 2))
print(repr(random_arr))

0
3
5
array([[11, 11],
       [-2,  9]], dtype=int32)
